"""empty message

Revision ID: 845846d929b5
Revises: f4d771400d28
Create Date: 2021-01-09 03:22:20.792293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '845846d929b5'
down_revision = 'f4d771400d28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'website')
    # ### end Alembic commands ###
