"""empty message

Revision ID: 960d1cd4f761
Revises: c1633a3ccba4
Create Date: 2021-01-08 22:07:09.572988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '960d1cd4f761'
down_revision = 'c1633a3ccba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
